before_script:
    - echo 'Deploy to test server'
    ## Install ssh-agent if not already installed
    - 'which ssh-agent || ( yum update -y && yum install openssh-client -y )'
    ## Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    ## Create the SSH directory and give it the right permissions
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    ## see who am i =))
    - whoami

# For test server
deploy-test:
  before_script:
    - echo 'Deploy to test server'
    ## Go to project folder
    - cd /var/www/html/mailserver
  script:
    # just run make :))
    - make deploy-test
  tags:
    - test
  only:
    - test-server

# For production server
deploy-production:
  before_script:
    ## Go to project folder
    - cd /var/www/html/mailserver
  script:
    # just run make :))
    - make deploy-production
  tags:
    - production
  only:
    - master